"""create password_analyses table

Revision ID: dcfeecf21552
Revises: 
Create Date: 2026-05-16 14:18:37.671811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfeecf21552'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entropy_bits', sa.Float(), nullable=False),
    sa.Column('pool_size', sa.Integer(), nullable=False),
    sa.Column('has_lowercase', sa.Boolean(), nullable=False),
    sa.Column('has_uppercase', sa.Boolean(), nullable=False),
    sa.Column('has_digits', sa.Boolean(), nullable=False),
    sa.Column('has_symbols', sa.Boolean(), nullable=False),
    sa.Column('strength_label', sa.String(length=50), nullable=False),
    sa.Column('strength_color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_analyses')
    # ### end Alembic commands ###
